### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by tuxkernel** [MayeulC/Saitek#17]
Nice piece of software. Thanks!

https://how-to-fix-mad-catz-rat7-on-linux.blogspot.com/

Tuxkernel...

**Comment by MayeulC** [comment]
Hey, you're welcome ;)

Nice blog post, I guess I need to have a look at my polling rate...

**Comment by tuxkernel** [comment]
Hi @MayeulC 

Maybe, only if you're gaming player. Consider you, add this info (mouse polling rate) to README.md as a option. Thanks again for this nice piece of software ;-)´

Tuxkernel...
