### ISSUE TITLE
RAT7

### ISSUE THREAD

**Issue by Milkman00** [MayeulC/Saitek#2]
I'm thinking this will easily work with the rat 7 as it's just the 9 is the wireless version of the 7.
Will be checking this out at home in the next couple days...
Any knowledge of this?

**Comment by MayeulC** [comment]
Sorry for the delay.
I don't own a R.A.T 7 (although I might be able to borrow one from a friend), so I can't guarantee this would easily work; but it would probably just need some minor tweaks.
Of course, if you can try it out with a R.A.T 7, it would be perfect. I would like to know how your experiments went.

**Comment by sorinnn** [comment]
... it is working actually with RAT 7.. I just set up the battery level to 100 (no need for wired mouse) ..and I've changed DPI range to 6400 
works well .. 

Can you guys do some autodetection  routine to check which kind of RAT is used ? - then this routine can set up the Titlebar text (and also disable the battery level check .. ). 

My question is if this little app can be themed - I can make some backgrounds, scrollbars, etc to look like Mad Catz original product. 

Maybe later we can connect this app with a key mapping linux software (I use now xbindkeys with xev and xdotool - therefore I've placed 3 shots rapid fire on the AIM button [the red one]) - so this can become a very capable app.

**Comment by kc14** [comment]
I have a MadCatz R.A.T. 7 Contagion. I am trying to configure it under Mac OS X 10.11.4 El Capitan. I have installed python 3.5.1, qt5 (5.6.0), libusb1 and I can run the script. But when I call:

`sudo python3 ratctl.py`

it fails with the following error message:

`Could not acquire device handle. Please ensure that it is correctly plugged in and that you have the appropriate rights.`

Any ideas what I can do?

**Comment by MayeulC** [comment]
Hello, 
Could you please try the script from the new_VID branch ? https://github.com/MayeulC/Saitek/tree/new_VID

If it still doesn't work, could you provide me your vendor and device IDs via `lsusb` ( it should look like 06a3:0cfa or 0738:1709 or similar).
I am planning some major improvements (reflecting what @sorinnn said), but I am afraid I won't be able to do so before July.

**Comment by MayeulC** [comment]
Closing the issue, as it will probably work now. If that's not the case, feel free to reopen it.

@kc14, could you open a separate issue with the output from the `lsusb` command or equivalent?
(A quick google search showed `ioreg -p IOUSB -l -w 0`, that might do the trick; I only need the USB IDs).
