### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by MayeulC** [MayeulC/Saitek#6]
The name was intended to be a placeholder. And I think we should rename `configurator.py` to something more obvious, like `rat-config` or `saitek-cfg`. 
As per #5, I would like to make this tool more general than just dedicated to R.A.T. devices, like bringing in compatibility with cyborg keyboards.
Do you have some naming suggestions you might want to let me know?

**Comment by CommanderAlchemy** [comment]
Well following with other pkgs, how about ratctrl / madctrl / cyborgctrl

**Comment by MayeulC** [comment]
Yep, `ratctl` sounds quite good in my opinion. At least for the R.A.T. configuration tool. 
Then, cyborgctl (or cyborgdaemon) might be more appropriate for the keyboard manager I have yet to finalize.

**Comment by MayeulC** [comment]
As the renaming is already effective since 2a95b1928561a5d50a11245791d855122a6657dd, I close the issue.
Also, sorry for missing out the "r" in "ctrl". I am just more used to commands that end with "ctl". Take for example (a controversial one) `systemctl`.
