### ISSUE TITLE
No module name usb1

### ISSUE THREAD

**Issue by alphaphee** [MayeulC/Saitek#7]
When I try to run ./configurator.py I get the following error:

``` sh
Traceback (most recent call last):
  File "./configurator.py", line 13, in <module>
    import usb1
ImportError: No module named 'usb1'
```

I am not very good with python, what should I do? 

my `lsusb` output: 

``` sh
Bus 005 Device 002: ID 8087:8000 Intel Corp. 
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0a92:00e1 EGO SYStems, Inc. 
Bus 001 Device 006: ID 0738:1709 Mad Catz, Inc. 
Bus 001 Device 009: ID 044f:b326 ThrustMaster, Inc. 
Bus 001 Device 008: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

edit: I tried both `pip install libusb1` and downloading and installing latest libusb1 source from github but the error persists

edit2: installed `pyusb` as well and replaced the mouse ID in the python code, with the output from `lsusb` but I still get the same error

**Comment by MayeulC** [comment]
You're right, I got this error as well today when trying to run it. For me, `sudo pip install libusb1` did the trick. If it works for you as well, I might add an entry in the readme.

**Comment by alphaphee** [comment]
Yes, sadly the problem persists. I also made sure that $PYTHONPATH points to python2.7 library (where libusb1 is located) but no luck with that either.

**Comment by MayeulC** [comment]
Actually, the program uses python3 :)
So, please make sure that pip installs the correct usb1 library.
You might have to use the pip3 binary, or pip-3.x, depending on your distro.

**Comment by alphaphee** [comment]
Oh, you were completely right. Somehow I missed that. :)
Please add it to the readme file. Thank you for your help.
